### PR TITLE
dccs: update token manager state position

### PR DESCRIPTION
**Pull request by hadv**

### CODE REVIEW

**Comment by hadv** [comment]
> Can you move these to other repo? They can always be accessed by relative path.

path is not the problem, put on same repo is only for convenience when deploying testnet :)

**Comment by Zergity** [comment]
> > Can you move these to other repo? They can always be accessed by relative path.
> 
> path is not the problem, put on same repo is only for convenience when deploying testnet :)

I strongly recommend to separate data and logic code. Even the go-ethereum's testdata is put in a separated repo, and be included into go-ethereum as a submodule.

It's as convenient as you address the data as "../data/FILE" instead of "data/FILE", where data is another repo you fetches along side with gonex.

Please consider it. It will make a very clean version control. I did the same with my test data in project https://github.com/nextyio/scripts

**Comment by hadv** [comment]
> > > Can you move these to other repo? They can always be accessed by relative path.
> > 
> > 
> > path is not the problem, put on same repo is only for convenience when deploying testnet :)
> 
> I strongly recommend to separate data and logic code. Even the go-ethereum's testdata is put in a separated repo, and be included into go-ethereum as a submodule.
> 
> It's as convenient as you address the data as "../data/FILE" instead of "data/FILE", where data is another repo you fetches along side with gonex.
> 
> Please consider it. It will make a very clean version control. I did the same with my test data in project https://github.com/nextyio/scripts

okay, for the time being, we removed the testnet data. Thinking about it later.

**Comment by Zergity** [comment]
Thank you.

**Pull request merged**
