### PR TITLE
[Refactor] Separation of data and logic for each hardfork

### PR DESCRIPTION
**Pull request by Zergity**
Consensus logic and data after each hardfork will be separated by #_file batch.

0_* are for the initial version.
1_* are for ThangLong consensus.
2_* will be the next consensus version.

ThangLong consensus contract deployment is the only part that mixed in between version 0 and 1, because the deployment happen in the block version before that. All next hardfork codes will be fully separated by utilizing engine.Initilize interface.

### CODE REVIEW

**Comment by hadv** [comment]
> ThangLong consensus contract deployment is the only part that mixed in between version 0 and 1, because the deployment happen in the block version before that. All next hardfork codes will be fully separated by utilizing engine.Initilize interface.

The next one may still need to upgrade contract before the checkpoint, due to we need it available on the hardfork block also

**Comment by Zergity** [comment]
> > ThangLong consensus contract deployment is the only part that mixed in between version 0 and 1, because the deployment happen in the block version before that. All next hardfork codes will be fully separated by utilizing engine.Initilize interface.
> 
> The next one may still need to upgrade contract before the checkpoint, due to we need it available on the hardfork block also

Initlizize is run before any tx applied, so it's safe for all consensus operation, including deployment there, right in the hardfork block.

**Comment by hadv** [comment]
it's okay but it's only the physical separate. Our main pain is if/else inside the consensus method :)

**Comment by Zergity** [comment]
> it's okay but it's only the physical separate. Our main pain is if/else inside the consensus method :)

All if-else stays in dccs.go/snapshot.go, and I can't think of any better way for now.

**Comment by hadv** [comment]
> Initlizize is run before any tx applied, so it's safe for all consensus operation, including deployment there, right in the hardfork block.

I mean, can we upgrade contract and use it at the same block?

**Comment by Zergity** [comment]
> > Initlizize is run before any tx applied, so it's safe for all consensus operation, including deployment there, right in the hardfork block.
> 
> I mean, can we upgrade contract and use it at the same block?

Definitely. I did it with Endurio and it works fine.

**Comment by hadv** [comment]
> > > Initlizize is run before any tx applied, so it's safe for all consensus operation, including deployment there, right in the hardfork block.
> > 
> > 
> > I mean, can we upgrade contract and use it at the same block?
> 
> Definitely. I did it with Endurio and it works fine.

okay, it's easy for test on `fast` branch but in the `Endurio` you deploy it and never use it in the block

**Comment by Zergity** [comment]
> Basically, It's good for us to reconstruct the source code of dccs. By the way, dont know separate by prefix filename or separate by sub-folder is better? :)

Changing folder will make the package structure changed. How do you do that and key they all in the one package?

**Comment by hadv** [comment]
> Changing folder will make the package structure changed. How do you do that and key they all in the one package?

No, we still use the same package `dccs` for all sub-folder I mean

**Comment by Zergity** [comment]
> > Changing folder will make the package structure changed. How do you do that and key they all in the one package?
> 
> No, we still use the same package `dccs` for all sub-folder I mean

Go spec specifies that **"An implementation may require that all source files for a package inhabit the same directory."** [Package clause](https://golang.org/ref/spec#Package_clause). And last time I checked, it's not possible for official golang compiler.

**Comment by hadv** [comment]
> Go spec specifies that **"An implementation may require that all source files for a package inhabit the same directory."** [Package clause](https://golang.org/ref/spec#Package_clause). And last time I checked, it's not possible for official golang compiler.

We may misunderstand the meaning of that statement. It seems only need to in the same root folder. For example, all the cmd files have the same package `main` 

https://github.com/nextyio/gonex/tree/master/cmd

**Comment by Zergity** [comment]
> > Go spec specifies that **"An implementation may require that all source files for a package inhabit the same directory."** [Package clause](https://golang.org/ref/spec#Package_clause). And last time I checked, it's not possible for official golang compiler.
> 
> We may misunderstand the meaning of that statement. It seems only need to in the same root folder. For example, all the cmd files have the same package `main`
> 
> https://github.com/nextyio/gonex/tree/master/cmd

main package usually doesn't need to call each other, it mays have special treatment. Becase I try to move 0_* to dccs/0 subfolder, keeping the package name as dccs, but they don't compile.

**Comment by hadv** [comment]
> main package usually doesn't need to call each other, it mays have special treatment. Becase I try to move 0_* to dccs/0 subfolder, keeping the package name as dccs, but they don't compile.

not sure, dont know why this is working? https://github.com/nextyio/gonex/tree/master/crypto/bn256

**Comment by hadv** [comment]
> > main package usually doesn't need to call each other, it mays have special treatment. Becase I try to move 0_* to dccs/0 subfolder, keeping the package name as dccs, but they don't compile.
> 
> not sure, dont know why this is working? https://github.com/nextyio/gonex/tree/master/crypto/bn256

ah, it may in the same package but difference implementation

**Pull request merged**
