### PR TITLE
core, cmd/puppeth: implement constantinople fix, disable EIP-1283

### LINKED ISSUE #80: core, puppeth: implement constantinople fix, disable eip 1283
We will enable Constantinople, Petersburg and ThangLong HardFork at the same block for nexty mainnet

https://github.com/ethereum/go-ethereum/pull/18486

https://github.com/ethereum/EIPs/pull/1716

### PR DESCRIPTION
**Pull request by hadv**
to resolve #80

### CODE REVIEW

**Comment by Zergity** [comment]
Did you miss this change? https://github.com/ethereum/go-ethereum/pull/18486/files#diff-3e8301305b1dc6d3f96fbe3429cda929

**Comment by Zergity** [comment]
Link this PR which you have included in this PR for reference: https://github.com/ethereum/go-ethereum/pull/18344

**Comment by hadv** [comment]
> Did you miss this change? https://github.com/ethereum/go-ethereum/pull/18486/files#diff-3e8301305b1dc6d3f96fbe3429cda929

I ignore this because it depends on other PR to introduce an option to overwrite the constantinople hardfork block number

**Comment by hadv** [comment]
> Link this PR which you have included in this PR for reference: [ethereum/go-ethereum#18344](https://github.com/ethereum/go-ethereum/pull/18344)

yeah, they commit some selected PRs for 1.8.21 for quick release to postpone constantinople hardfork on ethereum mainnet then when make PR for master branch, they also include my fix also. But I remember that I already fix it in a branch to make our testnet but cannot found it yesterday.

**Comment by Zergity** [comment]
LGTM

**Pull request merged**
