### PR TITLE
binding code for nexty governance and token smart contract 

### LINKED ISSUE #140: Move the nexty governance smart contract to gonex for pre-hardfork deployment
We need to generate go binding code for latest version of nexty governance smart contract https://github.com/nextyio/nexty-governance to deploy and use it as consensus endpoint from the ThangLong hardfork

### LINKED ISSUE #149: deploy NTF token on genesis for testnet
For convenience for both mainnet and testnet, we will introduce a new option to deploy NTF token for testnet on the genesis block via puppeth's genesis wizard to integrate it with nexty governance. 

Due to we already deploy NTF token on mainnet so for simplify the code base, we will deploy NTF token on testnet with the same address that already deployed on mainnet

### PR DESCRIPTION
**Pull request by hadv**
to fix #149 and fix #140

### CODE REVIEW

**Comment by Zergity** [comment]
Since it's a smart contract, much effort is spent to validate the code. I think we should create a MAKE task to auto-generate the go binding contract using abigen instead of committing it in. Require less work to validate and verify code on each change.

**Comment by Zergity** [comment]
Do we need MultiOwnable now? Does the contract need owners?

**Comment by hadv** [comment]
> Since it's a smart contract, much effort is spent to validate the code. I think we should create a MAKE task to auto-generate the go binding contract using abigen instead of committing it in. Require less work to validate and verify code on each change.

Dont understand what you mean. The contract is consensus and it is a must we need to do, including code audit and validation. abigen is local task then commit binding code for using is good way. ethereum also do the same way for their smart contracts.

**Comment by hadv** [comment]
> Do we need MultiOwnable now? Does the contract need owners?

I dont know, I get the code that already deployed on the mainnet then we cannot make any comments now.

**Comment by Zergity** [comment]
> local

I mean we could do like this:
1. Commit the sol source.
2. Create a MAKE task, to generate the go binding before building geth.

That way, each time there's a change in the sol code, we don't need to verify the go code of it.

But since we don't have any plan to change the NTF contract logic, so it could be not necessary.

**Comment by Zergity** [comment]
> > Do we need MultiOwnable now? Does the contract need owners?
> 
> I dont know, I get the code that already deployed on the mainnet then we cannot make any comments now.

Yes, nevermind. LGTM.

**Comment by hadv** [comment]
@Zergity PTAL ;)

**Comment by hadv** [comment]
> Can you refactor to share the code for new contract binding with TLPreparation logic?

hmm, cannot make a common code due to each contract have it own init params then it will become complicated to make one for all

**Comment by hadv** [comment]
I put binding code for nexty governance contract to implement #140 also, PTAL

**Comment by Zergity** [comment]
@hadv PTAL

**Comment by hadv** [comment]
> @hadv PTAL

cool, thanks!

**Comment by Zergity** [comment]
> > @hadv PTAL
> 
> cool, thanks!

If you are ok with the refactor, we need to move the method to some commonplace. Because it's not specific to a single consensus.

**Comment by hadv** [comment]
> If you are ok with the refactoring, we need to move the method to some commonplace. Because it's not specific to a single consensus.

yep, and rename the function to `DeployContract()`

**Comment by Zergity** [comment]
> > If you are ok with the refactoring, we need to move the method to some commonplace. Because it's not specific to a single consensus.
> 
> yep, and rename the function to `DeployContract()`

Yes, please do it. ``consensus/misc/forks.go`` is a good place to move to. Or a new file: ``consensus/misc/contract.go`` is also not bad.

**Comment by hadv** [comment]
> Yes, please do it. `consensus/misc/forks.go` is a good place to move to. Or a new file: `consensus/misc/contract.go` is also not bad.

I dont think it should belong to consensus then I move it to common package, plz check it out!

**Pull request merged**
